name: CI

on:
  push:
    branches:
       - main
env:
   APP_ENV: test
jobs:
  test:
     runs-on: ubuntu-latest

     steps:
        - name: Checkout code
          uses: actions/checkout@v6
          
        - name: Setup Node.js
          uses: actions/setup-node@v6
          with:
             node-version: ${{ vars.NODE_VERSION }}    

        - name: Install dependencies
          run: npm install

        - name: Run tests
          run: npm test

        - name: Test Secret
          run: 'echo "Secret exists: $TEST_SECRET"'
          env:
             TEST_SECRET: ${{ secrets.TEST_SECRET }}
        - name: Check environment
          run: echo "Environment is $APP_ENV"
          
  deploy-check: 
      needs: 
         - test
         - code-quality
      runs-on: ubuntu-latest

      steps:
        - name: Deploy Check
          run : echo "Test passed, deployment can proceed"
          
  code-quality: 
      runs-on: ubuntu-latest

      steps:
        - name: Code Quality Check
          run : echo "Code Quality Check Passed"
        
      
